sudo: false
language: go
go:
  - 1.11
  - "1.10"
  - 1.9
  - master

cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg

before_install:
  - go get -t -v ./...

script:
  - go vet ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
    - paul.vanbrouwershaven@globalsign.com
    on_success: never
    on_failure: change
