sudo: false
language: go
go:
  - 1.11
  - "1.10"
  - master

cache:
  directories:
    - $GOPATH/pkg

before_install:
  - go get -t ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
